apps/contact_us/urls.py
from django.urls import path

from apps.contact_us import views

app_name = "contactus"

urlpatterns = [
    path("contactus/", views.create, name="index"),
]

apps/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("registration/", views.RegisterFormView.as_view(), name="registration"),
    path("details/<int:pk>", views.UserDetailView.as_view(), name="details"),
    path("update/<int:pk>", views.UserUpdateView.as_view(), name="update"),
    path("delete/<int:pk>", views.UserDeleteView.as_view(), name="delete"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import about


urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("users/", include("apps.users.urls")),
    path("admin/", admin.site.urls),
    path("about/", about, name="about"),
    path("contactus/", include("apps.contact_us.urls")),
    path("", include("apps.users.urls_root")),
]
#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contact_us/models.py
from django.db import models


class ContactUs(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    phone = models.CharField(max_length=13, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    question = models.TextField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.name} - {self.phone} - {self.email} - {self.question}"

    __repr__ = __str__

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    avatar = models.ImageField(
        max_length=255,
        upload_to="users/avatar/",
        blank=True,
        null=True,
    )

apps/contact_us/forms.py
from django.forms import ModelForm

from apps.contact_us.models import ContactUs


class ContactUsForm(ModelForm):
    class Meta:
        model = ContactUs
        fields = ["email", "name", "phone", "question"]

apps/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2", "avatar"]

apps/contact_us/views.py
from django.contrib import messages
from django.core.checks import CRITICAL
from django.shortcuts import render, redirect

from apps.contact_us.forms import ContactUsForm


def create(request):
    if request.method == "POST":
        form = ContactUsForm(request.POST)
        if not (request.POST.get("name").isalpha()):
            messages.add_message(request, CRITICAL, "Name must have only letters.")
            return redirect("contactus:index")
        if not (request.POST.get("phone").isdigit()):
            messages.add_message(request, CRITICAL, "Phone must have only numbers.")
            return redirect("contactus:index")
        if not (request.POST.get("email")):
            messages.add_message(request, CRITICAL, "Email must be not empty.")
            return redirect("contactus:index")
        if form.is_valid():
            form.save()
            messages.add_message(request, CRITICAL, "Your message was added.")
            return redirect("contactus:index")
    else:
        form = ContactUsForm()

        return render(request, "contact_us/form.html", {"form": form})

apps/users/views.py
from django.contrib.auth import get_user_model, login
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import FormView, DetailView, UpdateView, DeleteView

from apps.users.forms import UserRegisterForm

User = get_user_model()


def index(request: WSGIRequest):
    return render(
        request=request,
        template_name="index.html",
    )


class RegisterFormView(FormView):
    form_class = UserRegisterForm
    template_name = "registration/register.html"
    success_url = reverse_lazy("root:index")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("root:index")


class UserDetailView(DetailView):
    model = User
    template_name = "users/details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Details User"
        return context


class UserUpdateView(UpdateView):
    model = User
    template_name = "users/update.html"
    fields = ("username", "email", "first_name", "last_name", "avatar")
    success_url = reverse_lazy("root:index")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Update Details User"
        return context


class UserDeleteView(DeleteView):
    model = User

    success_url = reverse_lazy("root:index")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Delete Account"
        return context

core/views.py
from django.core.handlers.wsgi import WSGIRequest
from django.shortcuts import render


def about(request: WSGIRequest):
    return render(
        request=request,
        template_name="about.html",
    )

apps/templates/_helpers/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if title %}
            {{ title }} |
        {% endif %}
    </title>

    {# [connect_bootstrap]-[BEGIN] #}
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous"
    >
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"
    ></script>
    {# [connect_bootstrap]-[END] #}
    <link
            href="{% static 'styles/index.css' %}"
            rel="stylesheet"
    >
    <link rel="shortcut icon" type="image/png" href="{% static "favicon.png" %}">
</head>
<body>
<div class="container-fluid">
    {% include '_helpers/_header.html' %}

    {% block content %}
        Hello!
    {% endblock %}
    {% include '_helpers/_footer.html' %}
</div>
</body>
</html>

apps/templates/_helpers/_footer.html
{% load static %}
<footer>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <p class="footer">Copyright@2023</p>
         <li>
                <a class="nav-link" href="{% url 'contactus:index' %}">Contact Us</a>
         </li>
    </nav>
</footer>

apps/templates/_helpers/_header.html
{% load static %}
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <img src="{% static "icons8-hadoop-distributed-file-system-144.svg" %}">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About Us</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav">
            <div class="right">
            {% if user.is_authenticated %}
            <div>
                <p>{{ user.username }}</p>
                </div>
                    <a type="button" class="btn btn-warning" href="{% url "logout" %}">Log Out</a>
                    <a type="button" class="btn btn-primary" href="{% url "users:details" pk=user.id %}">Details</a>
            {% else %}
                <p>Gest</p>
                <a type="button" class="btn btn-primary" href="{% url "login" %}">LogIn</a>
                <a type="button" class="btn btn-primary" href="{% url "users:registration" %}">Registration</a>
            {% endif %}
            </div>
        </ul>
    </nav>
</header>

apps/templates/about.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <h3>
        About us
    </h3>
    <div>
       BASE PROJECT
    </div>
{% endblock %}

apps/templates/contact_us/form.html
{% extends '_helpers/_base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    {% if user.is_authenticated %}
    <h1>Contact us</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form|crispy }}
        {% if messages %}
        <ul class="messages my-color">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% else %}
        <h1>You should login or register to  see all staff!!</h1>
    {% endif %}
{% endblock %}

apps/templates/index.html
{% extends '_helpers/_base.html' %}

{% block content %}
    <div>
        Main page
    </div>
{% endblock %}

apps/templates/users/details.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <div class="col my-element-style">
        <div>
            {% if user.avatar %}
                <img src="{{ user.avatar.url }}" alt="Avatar" style="width: 20%;">
            {% endif %}
        </div>
    </div>
        <p>User name: {{ object.username }}</p>
        <p>First name: {{ object.first_name }}</p>
        <p>Last name: {{ object.last_name }}</p>
        <p>Email: {{ object.email }}</p>
        <p>Last login: {{ object.last_login }}</p>
        <p>Date registration: {{ object.date_joined }}</p>
    <a type="button" class="btn btn-primary" href="{% url "users:update" pk=object.id %}">Edit</a>
    <a type="button" class="btn btn-primary" href="/accounts/password_change/">Change password</a>
    {% if user.is_superuser %}
    <a type="button" class="btn btn-danger" href="{% url "users:delete" pk=object.id %}">Delete</a>
    {% endif %}
{% endblock %}

apps/templates/users/update.html
{% extends "_helpers/_base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{ form | crispy }}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

apps/templates/users/user_confirm_delete.html
{% extends "_helpers/_base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        <p>Are you sure you want to delete "{{ object }}"?</p>

        <button type="submit" class="btn btn-danger">Confirm</button>
    </form>
{% endblock %}